[package]
name = "aoc2024"
version = "2024.0.0"
edition = "2021"

description = ""
authors = [ "Tomas Forsblom-Strand <tomas@fik1.net>" ]

[dependencies]
itertools = "0.13.0"
num = "0.4.3"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "aoc"
harness = false